DECLARE
  CURSOR CONST_CURSOR IS
    SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE 
    FROM USER_CONSTRAINTS 
    WHERE CONSTRAINT_TYPE = 'U';
  CURSOR INDEX_CURSOR IS
    SELECT T1.INDEX_NAME
    FROM (SELECT INDEX_NAME, TABLE_NAME, 
                 LISTAGG(COLUMN_NAME, '/') 
                 WITHIN GROUP(ORDER BY COLUMN_NAME) COLUMNS
          FROM USER_IND_COLUMNS
          GROUP BY TABLE_NAME, INDEX_NAME) T1
    WHERE NOT EXISTS (SELECT 'X'
                      FROM USER_CONSTRAINTS T2, 
                           (SELECT CONSTRAINT_NAME, 
                                   LISTAGG(COLUMN_NAME, '/') 
                                   WITHIN GROUP(ORDER BY COLUMN_NAME) COLUMNS
                            FROM USER_CONS_COLUMNS
                            GROUP BY CONSTRAINT_NAME) T3
                      WHERE T2.CONSTRAINT_NAME = T3.CONSTRAINT_NAME
                      AND T2.CONSTRAINT_TYPE = 'P'
                      AND T3.COLUMNS = T1.COLUMNS
                      AND T2.TABLE_NAME = T1.TABLE_NAME);
BEGIN
  EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
  FOR C IN CONST_CURSOR LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE '||C.TABLE_NAME||' DROP CONSTRAINT '||C.CONSTRAINT_NAME;
  END LOOP;
  FOR C IN INDEX_CURSOR LOOP
    EXECUTE IMMEDIATE 'DROP INDEX '||C.INDEX_NAME;
  END LOOP;
END;
/